### PR TITLE
implementation of calendar and scheduling use cases

### PR DESCRIPTION
**Pull request by celinelumqr**
Main functionality of feature 2 (personal calendar and task scheduling) implemented.

Tests and additional features TBA.

### CODE REVIEW

**Comment by celinelumqr** [comment]
checks are failing because of incompatibility with current state of StudentUser's workingHours, will update when StudentUser's edits are merged into main

**Review by alyson647 — APPROVED** [review]
Generally speaking, the code packaging and structure follows clean architecture and SOLID. The use cases contain all functionalities that scheduling tasks need. You have very good documentation in all your code, making it easy to understand what each method is doing and the purpose of each class. I like that you included comments in your UI classes since it shows what each section is doing. One note that I have is that you have a presenter as an instance variable in your interactor use case layer and that might be a violation of clean architecture since you’re interacting with a class in an outer layer. There is a lack of testing but it is good that you acknowledged what you're missing. Otherwise, everything looks good and I’ll approve this pull request.

**Comment by TiareMar** [comment]
Code Style:
- all naming conventions of packages, classes, variables and methods are adhered to
- names are consistent and inform the code reader about the function and use of methods, classes, attributes and methods, adding to readability and maintainability of code
- packaging organizes classes in a way that makes sense and makes code easy to find

Clean Architecture and SOLID:
- good adherence to clean architecture and proper dependency directions
- no blatant violations of SOLID principles
- in particular, good use of dependency inversion to maintain clean architecture with SchedulerPresenter and ScheduleConflictPresenter providing interfaces for the formatters in the UI layer (however does this skip the interface adapter layer?)

Documentation:
- Extremely thorough documentation throughout code makes the function of every class and method very easy to determine 

Working functionality of use cases is convincing and no obvious areas where code breaks were noted. Overall, good job!
Impressive UI code contributed too.
Before final submission, testing files for both scheduler and schedule conflict use cases should be added (as noted in your comments).

**Review by TiareMar — APPROVED** [review]

**Comment by celinelumqr** [comment]
closed upon branch deletion to resolve merge conflicts and issues with git.

**Pull request closed without merging**
