### PR TITLE
Feature 5 - scheduling collaborative tasks use cases

### PR DESCRIPTION
**Pull request by alyson647**
This is a pull request for the scheduling collaborative tasks feature that allows the user to schedule a collaborative task by entering the required information (task title).

In this branch I have the CollaborativeScheduling use case, and the Scheduling use case, with their associated input boundary, output boundary, request model, and response model. As well as the screen where the user inputs the information and the controller and presenter.

There's still some things I need to fix/figure out.

Current issues:
- Lack of documentation and testing
- After the user chooses the times they want to schedule the collaborative task, that information needs to be passed to the SchedulerInteractor use case in feature 3 in order to add it to the UI, we need to figure out how to pass the information on
- Need to fix the UI to make sure it's doing what I want

### CODE REVIEW

**Review by celinelumqr — APPROVED** [review]
As you mentioned, the test class has yet to be implemented. There is also a lack of documentation in general throughout the code, though the class/method/attribute names are clear enough that I can still get a good sense of what the code is doing. 

I'm approving this PR as the missing tests and documentation can be added later and the main priority is to get the feature implemented in the main code.

**Review by CC-3636 — COMMENTED** [review]
Overall comments:
- the internal comments helped me understand the code a lot better, but more javadoc comments would be good
- I'd recommend taking a look at your import statements--your ScheduleTaskController imports entities, which skips a layer in the Clean Architecture framework. What I did to get around this was to use the UserRegSaveRequest class (which is the parent to StudentSaveRequest and InstructorSaveRequest classes)--this class is like a transient data storage class. It stores all of the same data as the StudentUser and InstructorUser entities, but is not actually an entity. 
- although technically the ScheduleTaskRequestModel is in the use case layer, I don't think it should be importing entities. The Clean Architecture textbook did mention re. Request & Response Models that "You might be tempted to have these data structures contain references to Entity objects....Over time they will change for very
different reasons, so tying them together in any way violates the Common
Closure and Single Responsibility Principles."

**Review by TiareMar — DISMISSED** [review]
As mentioned, complete java documentation and testing still needs to be done. However, some informal comments helped me figure out what was going on and where you still had to figure some things out.

Overall, pretty good clean architecture adherence. In CollaborativeSchedulingPresenterInterface.java, I also had the same confusion as you about going form the presenter to the view. I think it might help to look at this piazza post (which is kind of vague but might give you a better idea) if you haven't already: [this one](https://piazza.com/class/l5v1b8gfz6b60m/post/469).

Good packaging and naming conventions.

Although work still needs to be done, I'm approving this pr in the interest of getting a working program for us first that we can improve on later.

**Review by sshmuylovich — COMMENTED** [review]
- As mentioned in other code reviews, the informal comments definitely make the code more readable but I think good Java documentation would be hugely beneficial. 
- From what I see, there are no glaring clean architecture violations. 
- We talked in tutorial about adding startTime and endTime as instance attributes of CollaborativeTask so that together with recurring and frequency the task can be scheduled repetitively. 
- We also agreed to limit the program by only allowing the one-time time block to be repeated on a frequency (i.e. if the frequency is monthly, there is only one meeting per month). 
- Remember: only the leader of the CollaborativeTask should have the ability to schedule it.
- What happens if a user is added or removed from a Collaborative Task? How are their schedule(s) adjusted accordingly?

**Pull request closed without merging**
