### PR TITLE
Feature 2 - completed main use cases, made changes to Task (and subclasses) and TaskMap

### PR DESCRIPTION
**Pull request by yyutiw**
Fairly certain the controllers for the edit use cases break clean architecture, will work on that later
Exception cases are not yet handled

For UI portion: unsure of how to convert inputted values to LocalDateTimes, disable frequency until recurring is checked (event),  have default values in text fields, only allow certain characters in text fields (eg ints), BUT UI has barely been started so I will (hopefully) figure out solutions in the near future

Also have not created any tests yet or added javadocs to everything

### CODE REVIEW

**Review by celinelumqr — DISMISSED** [review]
As far as I can tell, the code lacks documentation for most classes outside of the entities. However, the class/method/attribute names are clear enough to somewhat understand what each class is doing.

I'll approve this PR as our priority right now is to get the feature implemented in the main code, but please remember to add the necessary documentation later/

**Review by jltng — APPROVED** [review]
Coding style: package, class, method, and attribute/variable names are clear and explicitly state the its functionality, and follows the Java naming convention. Code follows SOLID design principles.

Clean Architecture: Code adheres to Clean Architecture principles, with the flow between layers from UI/screens to use cases to entity present. 

Documentation: Little to no documentation for most files, but because of clear coding style the methods / functions were easy to follow along.

Approving the PR as there are no major issues with the functionality of the code, and issues can be fixed later with little to no effect on the other features.

**Review by CC-3636 — COMMENTED** [review]
Overall comments:
- pretty good adherence to clean architecture rules w.r.t. having the lower-level classes depend on the higher-level ones (i.e. not jumping levels, import statements look good) --though would you not need a Gateway for interacting with the Task database?
- event creation use case and assignment creation use case have good javadoc comments., but would say the Task Deletion use case package needs some more documentation when you're done working on it
- I know you're not done writing the tests but highly recommend testing out your exception cases, specifically for task creations and edits

**Review by jltng — APPROVED** [review]
LGTM!

**Review by celinelumqr — APPROVED** [review]

**Review by CC-3636 — DISMISSED** [review]
Overall comments:
- controller doesn't look like it violates CA (but I only took a quick glance)
- maybe try using DateTimeFormatter ?

**Review by sshmuylovich — APPROVED** [review]
- Good attention to clean architecture and SOLID. 
- Where there is Java Documentation, it is good but there could be more of it.
- Instance Attribute endReccuringBy that you commented out with a note that you may implement later. If you check out Collaborative Task, I have implemented a similar attribute as a deadline. After speaking with Alyson who is scheduling Collaborative Tasks she mentioned that this was an important attribute to have. It may be worth implementing but this is also something that can be implemented slightly later. 
- For my use cases, I may need some of your protected methods to be made public. Will let you know about this as it becomes clearer but this should be easy to push and merge later. 
- Overall, great job. Approved!

**Review by jltng — APPROVED** [review]
LGTM!

**Review by CC-3636 — APPROVED** [review]
looks good!

**Pull request merged**
