### PR TITLE
Add Preparatory interface, make small changes to Task

### PR DESCRIPTION
**Pull request by yyutiw**

### CODE REVIEW

**Review by celinelumqr — DISMISSED** [review]
Preparatory interface suits needs of Calendar feature

**Comment by alyson647** [comment]
For classes that implement Preparatory, I think those classes need an attribute of prep times scheduled. Like private ArrayList<ArrayList<LocalDateTime>> prepTimeScheduled.

**Comment by alyson647** [comment]
Sorry but I think prepTimeScheduled requires a getter method for both Test and Assignment classes.

**Comment by TiareMar** [comment]
I know we talked about the ids in tutorial today already, but I just realized that having the ids as a random string makes the progress tracker feature work a lot more difficult because there is essentially no efficient way to query through tasks to search for "all tasks for student x for course y" for example. In fact, it might not be possible because tasks don't carry a lot of identifying information (task titles can be duplicated across all users and there is no course attribute for tasks...)

**Review by celinelumqr — DISMISSED** [review]

**Review by TiareMar — DISMISSED** [review]

**Review by alyson647 — DISMISSED** [review]

**Review by CC-3636 — APPROVED** [review]

**Review by celinelumqr — APPROVED** [review]

**Review by jltng — APPROVED** [review]
Looks good to me :)

**Pull request merged**
